# Generated by Django 5.0.6 on 2024-07-11 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_list", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("body", models.TextField(max_length=500)),
                ("attachment", models.FileField(upload_to="email_attachments/")),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emails.list"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_address", models.CharField(max_length=50)),
                (
                    "email_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="emails.list"
                    ),
                ),
            ],
        ),
    ]
