# Generated by Django 5.0.6 on 2024-07-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0005_sent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailtracking",
            old_name="Subscriber",
            new_name="subscriber",
        ),
    ]
