# Generated by Django 5.0.6 on 2024-07-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockanalysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="exchange",
            field=models.CharField(default="NASDAQ", max_length=100),
        ),
    ]
