# Generated by Django 5.0.6 on 2024-07-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockanalysis", "0002_alter_stock_country_alter_stock_exchange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="exchange",
            field=models.CharField(max_length=100),
        ),
    ]
