# Generated by Django 5.0.6 on 2024-07-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stockanalysis", "0004_stockdata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockdata",
            old_name="dividened_yield",
            new_name="avg_volume",
        ),
    ]
